name: Build Docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - version.txt
jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') }} # skip on documentation
    uses: ./.github/workflows/reusable_docker-build-and-push.yaml
    with: 
      publish: ${{ !startsWith(github.event.head_commit.message, 'ci') }} # don't publish image if only ci changed
