name: Lala

# When calling this workflow, ensure you use
#   secrets: inherit
# So the DOCKER_USERNAME and DOCKER_PASSWORD are available.

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        description: Wether to publish the image to Github Registry
        required: false
        default: false
      publish_dockerhub:
        type: boolean
        description: Whether to publish the image to Docker Hub (only if publish=true)
        required: false
        default: false
      version:
        type: string
        required: false
        description: the string to extract semver labels from. If empty, the ref/tag will be used (if on.tag trigger).
        default: ''

jobs:
  build_and_push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
            type=semver,pattern={{major}},value=${{ inputs.version }}
            type=ref,event=branch,suffix=-{{ sha }}
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/lala' || startsWith(github.ref, 'refs/tags/') }}
          flavor: |
            latest=false

      - name: Extract Docker metadata for Docker Hub
        if: ${{ inputs.publish_dockerhub }}
        id: meta_dockerhub
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
            type=semver,pattern={{major}},value=${{ inputs.version }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/lala' || startsWith(github.ref, 'refs/tags/') }}
          flavor: |
            latest=false

      - name: Add Docker Hub tags
        id: tags
        run: |
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo -e '${{ steps.meta.outputs.tags }}' >> $GITHUB_OUTPUT
          if [ -n '${{ inputs.publish_dockerhub }}' ]; then
            echo '${{ steps.meta_dockerhub.outputs.tags }}' >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Print tags
        run: |
          echo '${{ steps.tags.outputs.tags }}'
